//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicDiary.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int IdStudent { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Patronymic { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public int GroupId { get; set; }
        public int GenderId { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual Group Group { get; set; }
    }
}
