//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicDiary.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int IdTask { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public byte[] File { get; set; }
        public int MarkId { get; set; }
        public int TeacherGroupId { get; set; }
        public int CommentId { get; set; }
    
        public virtual Comment Comment { get; set; }
        public virtual Mark Mark { get; set; }
        public virtual TeacherGroup TeacherGroup { get; set; }
    }
}
